# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09e27e52bbf51378c14735f93a645f14b788ef9fcaa689bb4a62e6e9e8c77f6dbdab9280fad40889c135fd08cf032bac96231a85270d3cdb4bd28e83d7719165

test:
  secret_key_base: 21b60382fbb09bd542ad31d976431d9955bb5cf9793794d2841835afb2717c1f902ca946ce30823dfbe04fcc89dd6b45b1499f259a090df47c1633432011192f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
